export const destinations = [
  // MAASAI MARA REGION
  {
    id: 1,
    name: "Maasai Mara National Reserve",
    slug: "maasai-mara",
    region: "Rift Valley",
    country: "Kenya",
    coordinates: { lat: -1.4946, lng: 35.1439 },
    description: "World-famous for the Great Migration and exceptional wildlife viewing. Home to the Big Five and over 450 bird species.",
    shortDescription: "The crown jewel of Kenya's safari destinations",
    bestTimeToVisit: "July to October for the Great Migration",
    weather: "Warm days, cool nights. Average 25°C",
    activities: [
      "Game Drives",
      "Hot Air Balloon Safaris",
      "Maasai Village Visits",
      "Photography Safaris",
      "Night Game Drives",
      "Bush Dinners"
    ],
    wildlife: [
      "Lions",
      "Leopards",
      "Elephants",
      "Buffalo",
      "Rhinos",
      "Cheetahs",
      "Wildebeest",
      "Zebras",
      "Giraffes"
    ],
    image: "https://images.unsplash.com/photo-1534177616072-ef7dc120449d",
    gallery: [
      "https://images.unsplash.com/photo-1516426122078-c23e76319801",
      "https://images.unsplash.com/photo-1547970810-dc1eac37d174"
    ],
    tourCount: 24,
    hotelCount: 45,
    rating: 4.9,
    featured: true,
    established: 1961,
    area: "1,510 km²",
    entranceFees: {
      citizens: "KES 1,000",
      residents: "KES 4,000",
      nonResidents: "$80"
    },
    openingHours: "6:00 AM - 6:00 PM",
    parkHighlights: [
      "Great Migration River Crossings",
      "Big Five Sightings",
      "Balloon Safaris at Dawn",
      "Maasai Cultural Experiences"
    ]
  },
  {
    id: 2,
    name: "Masai Mara Conservancies",
    slug: "masai-mara-conservancies",
    region: "Rift Valley",
    country: "Kenya",
    coordinates: { lat: -1.4846, lng: 35.0892 },
    description: "Private conservancies bordering the Maasai Mara offering exclusive safari experiences with limited vehicle numbers.",
    shortDescription: "Exclusive wildlife viewing with fewer crowds",
    bestTimeToVisit: "Year-round, best June-October",
    weather: "Mild temperatures, 20-28°C",
    activities: [
      "Night Game Drives",
      "Walking Safaris",
      "Cultural Visits",
      "Private Sundowners",
      "Bush Breakfasts"
    ],
    wildlife: [
      "Black Rhino",
      "Wild Dogs",
      "Cheetah",
      "Leopard",
      "Elephant",
      "Lion"
    ],
    image: "https://images.unsplash.com/photo-1549362157-6c7e6e3e33e4",
    gallery: [],
    tourCount: 15,
    hotelCount: 28,
    rating: 4.8,
    featured: true,
    established: 2005,
    area: "100,000+ acres",
    parkHighlights: [
      "Exclusive Safari Experience",
      "Off-Road Driving Permitted",
      "Walking Safaris",
      "Night Game Drives"
    ]
  },
  {
    id: 3,
    name: "Oloololo Escarpment",
    slug: "oloololo-escarpment",
    region: "Rift Valley",
    country: "Kenya",
    coordinates: { lat: -1.3786, lng: 34.9882 },
    description: "Dramatic escarpment offering panoramic views of the Maasai Mara plains.",
    shortDescription: "Spectacular views over the Mara plains",
    bestTimeToVisit: "June-October for clear views",
    weather: "Cool at altitude, 15-25°C",
    activities: [
      "Scenic Drives",
      "Photography",
      "Sunset Viewing",
      "Picnic Spots"
    ],
    wildlife: ["Elephant", "Buffalo", "Giraffe", "Various Birds"],
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    gallery: [],
    tourCount: 8,
    hotelCount: 12,
    rating: 4.7,
    featured: false
  },

  // COASTAL REGION
  {
    id: 4,
    name: "Diani Beach",
    slug: "diani-beach",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -4.2770, lng: 39.5946 },
    description: "Pristine white sand beaches along the Indian Ocean with luxury resorts and water sports.",
    shortDescription: "Kenya's premier beach destination",
    bestTimeToVisit: "December to March, July to October",
    weather: "Tropical, 25-32°C year-round",
    activities: [
      "Snorkeling",
      "Scuba Diving",
      "Kite Surfing",
      "Deep Sea Fishing",
      "Boat Cruises",
      "Spa Treatments"
    ],
    wildlife: ["Dolphins", "Sea Turtles", "Tropical Fish"],
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd",
    gallery: [
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b"
    ],
    tourCount: 18,
    hotelCount: 85,
    rating: 4.9,
    featured: true,
    beaches: ["Diani Beach", "Galu Beach", "Tiwi Beach"],
    waterSports: ["Kitesurfing", "Windsurfing", "Jet Skiing", "Parasailing"]
  },
  {
    id: 5,
    name: "Watamu Beach",
    slug: "watamu-beach",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -3.3520, lng: 40.0165 },
    description: "Marine National Park with pristine beaches and coral reefs.",
    shortDescription: "Marine paradise and turtle sanctuary",
    bestTimeToVisit: "October-March",
    weather: "Tropical, 25-32°C",
    activities: [
      "Snorkeling",
      "Diving",
      "Boat Trips",
      "Turtle Watching",
      "Glass Bottom Boats"
    ],
    wildlife: ["Green Turtles", "Hawksbill Turtles", "Dolphins", "Whale Sharks (seasonal)"],
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206",
    gallery: [],
    tourCount: 14,
    hotelCount: 42,
    rating: 4.8,
    featured: true,
    marinePark: "Watamu Marine National Park",
    conservation: "Sea Turtle Conservation"
  },
  {
    id: 6,
    name: "Malindi",
    slug: "malindi",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -3.2198, lng: 40.1203 },
    description: "Historic Swahili town with Italian influence, beautiful beaches, and the Malindi Marine Park.",
    shortDescription: "Historic coastal town with Italian flair",
    bestTimeToVisit: "December-March",
    weather: "Tropical, 24-30°C",
    activities: [
      "Historical Tours",
      "Beach Activities",
      "Deep Sea Fishing",
      "Boat Trips"
    ],
    wildlife: ["Marine Life", "Birds"],
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b",
    gallery: [],
    tourCount: 12,
    hotelCount: 38,
    rating: 4.6,
    featured: false,
    historical: ["Gede Ruins", "Vasco da Gama Pillar", "Old Town"]
  },
  {
    id: 7,
    name: "Lamu Island",
    slug: "lamu-island",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -2.2697, lng: 40.9022 },
    description: "UNESCO World Heritage Site, the oldest Swahili settlement with traditional architecture and culture.",
    shortDescription: "UNESCO World Heritage Swahili settlement",
    bestTimeToVisit: "July-March",
    weather: "Tropical, 24-32°C",
    activities: [
      "Donkey Rides",
      "Dhow Cruises",
      "Historical Tours",
      "Swahili Cooking Classes",
      "Beach Activities"
    ],
    wildlife: ["Dolphins", "Sea Turtles"],
    image: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5",
    gallery: [],
    tourCount: 10,
    hotelCount: 25,
    rating: 4.9,
    featured: true,
    unesco: true,
    transportation: "Donkey taxis, boats (no cars)"
  },
  {
    id: 8,
    name: "Kilifi",
    slug: "kilifi",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -3.6316, lng: 39.8453 },
    description: "Picturesque creek town with mangrove forests and deepwater creek perfect for sailing.",
    shortDescription: "Scenic creek town with sailing paradise",
    bestTimeToVisit: "December-March",
    weather: "Tropical, 24-30°C",
    activities: [
      "Sailing",
      "Kayaking",
      "Boat Tours",
      "Mangrove Walks",
      "Snorkeling"
    ],
    wildlife: ["Mangrove Crabs", "Birds", "Marine Life"],
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd",
    gallery: [],
    tourCount: 8,
    hotelCount: 20,
    rating: 4.5,
    featured: false
  },
  {
    id: 9,
    name: "Tiwi Beach",
    slug: "tiwi-beach",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -4.2700, lng: 39.5800 },
    description: "Quieter alternative to Diani with beautiful white sands and relaxed atmosphere.",
    shortDescription: "Secluded beach paradise",
    bestTimeToVisit: "December-March",
    weather: "Tropical, 25-31°C",
    activities: [
      "Swimming",
      "Sunbathing",
      "Beach Walks",
      "Snorkeling"
    ],
    wildlife: ["Sea Turtles", "Tropical Fish"],
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206",
    gallery: [],
    tourCount: 6,
    hotelCount: 15,
    rating: 4.7,
    featured: false
  },

  // AMBOSELI & TSAVO REGION
  {
    id: 10,
    name: "Amboseli National Park",
    slug: "amboseli",
    region: "Rift Valley",
    country: "Kenya",
    coordinates: { lat: -2.6424, lng: 37.2625 },
    description: "Famous for large elephant herds and stunning views of Mount Kilimanjaro.",
    shortDescription: "Elephant paradise with Kilimanjaro backdrop",
    bestTimeToVisit: "June-October, January-February",
    weather: "Hot days, cool nights. 20-30°C",
    activities: [
      "Game Drives",
      "Elephant Research Center Visit",
      "Photography Safaris",
      "Maasai Village Tours",
      "Bird Watching"
    ],
    wildlife: [
      "Elephants",
      "Lions",
      "Cheetahs",
      "Buffalo",
      "Zebras",
      "Giraffes",
      "Hippos"
    ],
    image: "https://images.unsplash.com/photo-1549362157-6c7e6e3e33e4",
    gallery: [],
    tourCount: 18,
    hotelCount: 28,
    rating: 4.8,
    featured: true,
    area: "392 km²",
    landmark: "Mount Kilimanjaro Views"
  },
  {
    id: 11,
    name: "Tsavo East National Park",
    slug: "tsavo-east",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -2.7754, lng: 38.7510 },
    description: "Kenya's largest national park, known for the 'red elephants' and diverse landscapes.",
    shortDescription: "Land of red elephants and vast savannah",
    bestTimeToVisit: "June-October, January-February",
    weather: "Hot and dry, 25-35°C",
    activities: [
      "Game Drives",
      "Bird Watching",
      "Yatta Plateau Visit",
      "Lugard Falls",
      "Mudanda Rock"
    ],
    wildlife: [
      "Red Elephants",
      "Lions",
      "Leopards",
      "Buffalo",
      "Rhinos",
      "Giraffes",
      "Zebras"
    ],
    image: "https://images.unsplash.com/photo-1523805009345-7448845a9e53",
    gallery: [],
    tourCount: 22,
    hotelCount: 32,
    rating: 4.7,
    featured: true,
    area: "13,747 km²",
    landmarks: ["Yatta Plateau", "Lugard Falls", "Mudanda Rock"]
  },
  {
    id: 12,
    name: "Tsavo West National Park",
    slug: "tsavo-west",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -3.0238, lng: 38.0456 },
    description: "Dramatic landscapes with volcanic hills, Mzima Springs, and diverse wildlife.",
    shortDescription: "Volcanic landscapes and clear springs",
    bestTimeToVisit: "June-October",
    weather: "Hot days, cool nights",
    activities: [
      "Game Drives",
      "Mzima Springs Snorkeling",
      "Shetani Lava Flow Visit",
      "Chaimu Crater Hike",
      "Bird Watching"
    ],
    wildlife: ["Elephant", "Leopard", "Rhino", "Buffalo", "Hippo at Mzima Springs"],
    image: "https://images.unsplash.com/photo-1549362157-6c7e6e3e33e4",
    gallery: [],
    tourCount: 20,
    hotelCount: 28,
    rating: 4.8,
    featured: true,
    area: "9,065 km²",
    highlights: ["Mzima Springs", "Shetani Lava Flow", "Chaimu Crater"]
  },
  {
    id: 13,
    name: "Chyulu Hills",
    slug: "chyulu-hills",
    region: "Eastern",
    country: "Kenya",
    coordinates: { lat: -2.6000, lng: 37.8500 },
    description: "Volcanic mountain range with stunning views, part of the Tsavo ecosystem.",
    shortDescription: "Volcanic mountains with breathtaking views",
    bestTimeToVisit: "June-October",
    weather: "Cool at altitude, 15-25°C",
    activities: [
      "Hiking",
      "Horseback Safaris",
      "Cave Exploration",
      "Bird Watching",
      "Photography"
    ],
    wildlife: ["Elephant", "Buffalo", "Mountain Bongo", "Leopard"],
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    gallery: [],
    tourCount: 8,
    hotelCount: 12,
    rating: 4.6,
    featured: false
  },

  // LAKES REGION
  {
    id: 14,
    name: "Lake Nakuru National Park",
    slug: "lake-nakuru",
    region: "Rift Valley",
    country: "Kenya",
    coordinates: { lat: -0.3031, lng: 36.0800 },
    description: "Famous for flamingos and rhino sanctuary. A birdwatcher's paradise.",
    shortDescription: "Pink lake and rhino sanctuary",
    bestTimeToVisit: "Year-round",
    weather: "Mild, 15-28°C",
    activities: [
      "Game Drives",
      "Bird Watching",
      "Rhino Sanctuary Visit",
      "Baboon Cliff View",
      "Makalia Falls"
    ],
    wildlife: [
      "Flamingos",
      "White Rhino",
      "Black Rhino",
      "Lions",
      "Leopards",
      "Giraffes"
    ],
    image: "https://images.unsplash.com/photo-1455218873509-8097305ee378",
    gallery: [],
    tourCount: 16,
    hotelCount: 22,
    rating: 4.7,
    featured: true,
    area: "188 km²",
    birdSpecies: "Over 450 species"
  },
  {
    id: 15,
    name: "Lake Naivasha",
    slug: "lake-naivasha",
    region: "Rift Valley",
    country: "Kenya",
    coordinates: { lat: -0.7692, lng: 36.3588 },
    description: "Freshwater lake with hippos, boat rides, and nearby Crescent Island Game Sanctuary.",
    shortDescription: "Hippo haven and boat safaris",
    bestTimeToVisit: "Year-round",
    weather: "Pleasant, 15-28°C",
    activities: [
      "Boat Safaris",
      "Crescent Island Walk",
      "Hells Gate Visit",
      "Bird Watching",
      "Fishing"
    ],
    wildlife: ["Hippos", "Giraffes", "Zebras", "Over 400 Bird Species"],
    image: "https://images.unsplash.com/photo-1549362157-6c7e6e3e33e4",
    gallery: [],
    tourCount: 14,
    hotelCount: 35,
    rating: 4.6,
    featured: true,
    altitude: "1,884 m",
    attractions: ["Crescent Island", "Hells Gate National Park"]
  },
  {
    id: 16,
    name: "Lake Bogoria",
    slug: "lake-bogoria",
    region: "Rift Valley",
    country: "Kenya",
    coordinates: { lat: 0.2500, lng: 36.1000 },
    description: "Famous for hot springs, geysers, and large flamingo populations.",
    shortDescription: "Hot springs and flamingo paradise",
    bestTimeToVisit: "Year-round",
    weather: "Hot, 20-35°C",
    activities: [
      "Hot Springs Viewing",
      "Flamingo Watching",
      "Game Drives",
      "Bird Watching",
      "Photography"
    ],
    wildlife: ["Flamingos", "Greater Kudu", "Zebra", "Impala"],
    image: "https://images.unsplash.com/photo-1455218873509-8097305ee378",
    gallery: [],
    tourCount: 8,
    hotelCount: 5,
    rating: 4.5,
    featured: false,
    geothermal: "Hot springs and geysers"
  },
  {
    id: 17,
    name: "Lake Baringo",
    slug: "lake-baringo",
    region: "Rift Valley",
    country: "Kenya",
    coordinates: { lat: 0.6333, lng: 36.0833 },
    description: "Freshwater lake known for bird watching, boat rides, and crocodiles.",
    shortDescription: "Bird watcher's paradise",
    bestTimeToVisit: "Year-round",
    weather: "Hot, 20-35°C",
    activities: [
      "Boat Safaris",
      "Bird Watching",
      "Fishing",
      "Cultural Visits",
      "Camping"
    ],
    wildlife: ["Crocodiles", "Hippos", "Over 470 Bird Species"],
    image: "https://images.unsplash.com/photo-1549362157-6c7e6e3e33e4",
    gallery: [],
    tourCount: 6,
    hotelCount: 8,
    rating: 4.4,
    featured: false
  },
  {
    id: 18,
    name: "Lake Turkana",
    slug: "lake-turkana",
    region: "Northern",
    country: "Kenya",
    coordinates: { lat: 3.5000, lng: 36.0000 },
    description: "The world's largest permanent desert lake, known as the 'Jade Sea'.",
    shortDescription: "The Jade Sea - World's largest desert lake",
    bestTimeToVisit: "June-September",
    weather: "Extremely hot, 30-40°C",
    activities: [
      "Boat Trips",
      "Cultural Visits",
      "Fishing",
      "Fossil Hunting",
      "Photography"
    ],
    wildlife: ["Crocodiles", "Hippos", "Scorpions", "Birds"],
    image: "https://images.unsplash.com/photo-1549362157-6c7e6e3e33e4",
    gallery: [],
    tourCount: 4,
    hotelCount: 3,
    rating: 4.3,
    featured: false,
    unesco: true,
    size: "6,405 km²"
  },
  {
    id: 19,
    name: "Lake Victoria (Kenya)",
    slug: "lake-victoria-kenya",
    region: "Western",
    country: "Kenya",
    coordinates: { lat: -0.5000, lng: 34.5000 },
    description: "Africa's largest lake, shared with Uganda and Tanzania, rich in fish and culture.",
    shortDescription: "Africa's largest lake",
    bestTimeToVisit: "December-March",
    weather: "Tropical, 20-30°C",
    activities: [
      "Fishing",
      "Boat Trips",
      "Bird Watching",
      "Cultural Visits",
      "Sunset Cruises"
    ],
    wildlife: ["Nile Perch", "Tilapia", "Hippos", "Crocodiles"],
    image: "https://images.unsplash.com/photo-1455218873509-8097305ee378",
    gallery: [],
    tourCount: 8,
    hotelCount: 12,
    rating: 4.2,
    featured: false
  },

  // NORTHERN KENYA
  {
    id: 20,
    name: "Samburu National Reserve",
    slug: "samburu",
    region: "Rift Valley",
    country: "Kenya",
    coordinates: { lat: 0.6167, lng: 37.5333 },
    description: "Unique wildlife species found only in northern Kenya including Grevy's zebra and reticulated giraffe.",
    shortDescription: "Home of the Samburu Special Five",
    bestTimeToVisit: "June-October",
    weather: "Hot and dry, 25-35°C",
    activities: [
      "Game Drives",
      "Samburu Village Visits",
      "Bird Watching",
      "River Safaris",
      "Cultural Tours"
    ],
    wildlife: [
      "Grevy's Zebra",
      "Reticulated Giraffe",
      "Somali Ostrich",
      "Beisa Oryx",
      "Gerenuk",
      "Leopards",
      "Elephants"
    ],
    image: "https://images.unsplash.com/photo-1523805009345-7448845a9e53",
    gallery: [],
    tourCount: 14,
    hotelCount: 18,
    rating: 4.8,
    featured: true,
    specialFive: ["Grevy's Zebra", "Reticulated Giraffe", "Somali Ostrich", "Beisa Oryx", "Gerenuk"]
  },
  {
    id: 21,
    name: "Shaba National Reserve",
    slug: "shaba",
    region: "Eastern",
    country: "Kenya",
    coordinates: { lat: 0.6333, lng: 37.7667 },
    description: "Dramatic volcanic landscapes featured in 'Born Free' films.",
    shortDescription: "Dramatic volcanic landscapes",
    bestTimeToVisit: "June-October",
    weather: "Hot, 25-35°C",
    activities: [
      "Game Drives",
      "Bird Watching",
      "Photography",
      "Camel Safaris",
      "Cultural Visits"
    ],
    wildlife: ["Reticulated Giraffe", "Grevy's Zebra", "Leopard", "Cheetah"],
    image: "https://images.unsplash.com/photo-1549362157-6c7e6e3e33e4",
    gallery: [],
    tourCount: 8,
    hotelCount: 6,
    rating: 4.5,
    featured: false
  },
  {
    id: 22,
    name: "Buffalo Springs National Reserve",
    slug: "buffalo-springs",
    region: "Eastern",
    country: "Kenya",
    coordinates: { lat: 0.5500, lng: 37.6500 },
    description: "Adjacent to Samburu, known for its natural springs and diverse wildlife.",
    shortDescription: "Natural springs and diverse wildlife",
    bestTimeToVisit: "June-October",
    weather: "Hot, 25-35°C",
    activities: [
      "Game Drives",
      "Bird Watching",
      "Spring Visits",
      "Photography"
    ],
    wildlife: ["Elephant", "Lion", "Leopard", "Buffalo", "Giraffe"],
    image: "https://images.unsplash.com/photo-1523805009345-7448845a9e53",
    gallery: [],
    tourCount: 6,
    hotelCount: 4,
    rating: 4.4,
    featured: false
  },
  {
    id: 23,
    name: "Meru National Park",
    slug: "meru",
    region: "Eastern",
    country: "Kenya",
    coordinates: { lat: 0.0833, lng: 38.1667 },
    description: "Birthplace of 'Born Free', diverse landscapes from forests to rivers.",
    shortDescription: "Birthplace of Elsa the Lioness",
    bestTimeToVisit: "June-October",
    weather: "Hot, 20-35°C",
    activities: [
      "Game Drives",
      "Elsa's Grave Visit",
      "Bird Watching",
      "Fishing",
      "Bush Walks"
    ],
    wildlife: ["Elephant", "Lion", "Leopard", "Buffalo", "Rhino", "Giraffe"],
    image: "https://images.unsplash.com/photo-1549362157-6c7e6e3e33e4",
    gallery: [],
    tourCount: 10,
    hotelCount: 8,
    rating: 4.6,
    featured: false,
    famous: "Elsa the Lioness from 'Born Free'"
  },
  {
    id: 24,
    name: "Marsabit National Park",
    slug: "marsabit",
    region: "Eastern",
    country: "Kenya",
    coordinates: { lat: 2.3000, lng: 38.0000 },
    description: "Forest oasis in the desert with crater lakes and elephants.",
    shortDescription: "Desert oasis with crater lakes",
    bestTimeToVisit: "June-September",
    weather: "Cool at altitude, 15-25°C",
    activities: [
      "Game Drives",
      "Lake Visits",
      "Bird Watching",
      "Forest Walks"
    ],
    wildlife: ["Elephant", "Buffalo", "Greater Kudu", "Leopard"],
    image: "https://images.unsplash.com/photo-1549362157-6c7e6e3e33e4",
    gallery: [],
    tourCount: 4,
    hotelCount: 3,
    rating: 4.2,
    featured: false
  },
  {
    id: 25,
    name: "Losai National Reserve",
    slug: "losai",
    region: "Eastern",
    country: "Kenya",
    coordinates: { lat: 1.5000, lng: 37.5000 },
    description: "Remote wilderness area in northern Kenya with unique wildlife.",
    shortDescription: "Remote northern wilderness",
    bestTimeToVisit: "June-September",
    weather: "Hot, 25-40°C",
    activities: [
      "Game Drives",
      "Cultural Visits",
      "Bird Watching",
      "Photography"
    ],
    wildlife: ["Grevy's Zebra", "Oryx", "Gerenuk", "Somali Ostrich"],
    image: "https://images.unsplash.com/photo-1523805009345-7448845a9e53",
    gallery: [],
    tourCount: 2,
    hotelCount: 1,
    rating: 4.0,
    featured: false
  },

  // CENTRAL KENYA & MT KENYA
  {
    id: 26,
    name: "Mount Kenya National Park",
    slug: "mount-kenya",
    region: "Central",
    country: "Kenya",
    coordinates: { lat: -0.1500, lng: 37.3000 },
    description: "Africa's second-highest mountain, a UNESCO World Heritage Site with diverse ecosystems.",
    shortDescription: "Africa's second highest peak",
    bestTimeToVisit: "January-February, July-October",
    weather: "Cold at altitude, 0-20°C",
    activities: [
      "Mountain Climbing",
      "Hiking",
      "Bird Watching",
      "Wildlife Viewing",
      "Camping"
    ],
    wildlife: ["Elephant", "Buffalo", "Bushbuck", "Hyena", "Over 130 Bird Species"],
    image: "https://images.unsplash.com/photo-1547483238-f400e65ccd56",
    gallery: [],
    tourCount: 12,
    hotelCount: 15,
    rating: 4.8,
    featured: true,
    altitude: "5,199 m",
    unesco: true
  },
  {
    id: 27,
    name: "Aberdare National Park",
    slug: "aberdare",
    region: "Central",
    country: "Kenya",
    coordinates: { lat: -0.4167, lng: 36.7000 },
    description: "Mountain forest park with waterfalls, unique tree hotels, and rare wildlife.",
    shortDescription: "Mountain forest with tree hotels",
    bestTimeToVisit: "Year-round",
    weather: "Cool, 5-20°C",
    activities: [
      "Game Drives",
      "Tree Hotel Stays",
      "Waterfall Visits",
      "Trout Fishing",
      "Bird Watching"
    ],
    wildlife: ["Elephant", "Leopard", "Bongo", "Giant Forest Hog", "Colobus Monkey"],
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    gallery: [],
    tourCount: 10,
    hotelCount: 12,
    rating: 4.7,
    featured: true,
    treeHotels: ["The Ark", "Treetops"]
  },
  {
    id: 28,
    name: "Ol Pejeta Conservancy",
    slug: "ol-pejeta",
    region: "Central",
    country: "Kenya",
    coordinates: { lat: 0.0000, lng: 36.9333 },
    description: "Home to the last two northern white rhinos, chimpanzee sanctuary, and rhino conservation.",
    shortDescription: "Home of the last northern white rhinos",
    bestTimeToVisit: "Year-round",
    weather: "Mild, 15-28°C",
    activities: [
      "Game Drives",
      "Rhino Tracking",
      "Chimpanzee Sanctuary",
      "Night Game Drives",
      "Educational Tours"
    ],
    wildlife: ["Northern White Rhino", "Black Rhino", "Chimpanzees", "Lion", "Elephant"],
    image: "https://images.unsplash.com/photo-1549362157-6c7e6e3e33e4",
    gallery: [],
    tourCount: 12,
    hotelCount: 10,
    rating: 4.9,
    featured: true,
    conservation: "Last two northern white rhinos"
  },
  {
    id: 29,
    name: "Sweetwaters Game Reserve",
    slug: "sweetwaters",
    region: "Central",
    country: "Kenya",
    coordinates: { lat: 0.0333, lng: 36.9500 },
    description: "Part of Ol Pejeta, known for chimpanzee sanctuary and rhino conservation.",
    shortDescription: "Rhino conservation success story",
    bestTimeToVisit: "Year-round",
    weather: "Mild, 15-28°C",
    activities: [
      "Game Drives",
      "Chimpanzee Sanctuary",
      "Rhino Tracking",
      "Night Game Drives"
    ],
    wildlife: ["Chimpanzees", "Rhinos", "Elephants", "Lions", "Giraffes"],
    image: "https://images.unsplash.com/photo-1523805009345-7448845a9e53",
    gallery: [],
    tourCount: 8,
    hotelCount: 4,
    rating: 4.7,
    featured: false
  },
  {
    id: 30,
    name: "Mount Longonot National Park",
    slug: "mount-longonot",
    region: "Rift Valley",
    country: "Kenya",
    coordinates: { lat: -0.9167, lng: 36.4500 },
    description: "Volcanic crater mountain with hiking trails and views of the Rift Valley.",
    shortDescription: "Volcanic crater hike",
    bestTimeToVisit: "Year-round",
    weather: "Warm, 15-30°C",
    activities: [
      "Crater Rim Hiking",
      "Bird Watching",
      "Picnicking",
      "Photography"
    ],
    wildlife: ["Buffalo", "Zebra", "Giraffe", "Elusive Leopard"],
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    gallery: [],
    tourCount: 6,
    hotelCount: 3,
    rating: 4.5,
    featured: false,
    altitude: "2,776 m"
  },
  {
    id: 31,
    name: "Hells Gate National Park",
    slug: "hells-gate",
    region: "Rift Valley",
    country: "Kenya",
    coordinates: { lat: -0.9000, lng: 36.3167 },
    description: "One of the few parks where you can walk, cycle, and rock climb without predators.",
    shortDescription: "Walk and cycle with wildlife",
    bestTimeToVisit: "Year-round",
    weather: "Warm, 15-30°C",
    activities: [
      "Cycling",
      "Walking Safaris",
      "Rock Climbing",
      "Geothermal Spa Visit",
      "Bird Watching"
    ],
    wildlife: ["Zebra", "Giraffe", "Buffalo", "Antelope", "Over 100 Bird Species"],
    image: "https://images.unsplash.com/photo-1549362157-6c7e6e3e33e4",
    gallery: [],
    tourCount: 8,
    hotelCount: 4,
    rating: 4.6,
    featured: false,
    unique: "No predators - walk and cycle"
  },

  // WESTERN KENYA
  {
    id: 32,
    name: "Kakamega Forest",
    slug: "kakamega-forest",
    region: "Western",
    country: "Kenya",
    coordinates: { lat: 0.2833, lng: 34.8500 },
    description: "Kenya's only tropical rainforest, rich in primate species and birds.",
    shortDescription: "Kenya's only tropical rainforest",
    bestTimeToVisit: "December-March",
    weather: "Humid, 18-28°C",
    activities: [
      "Forest Walks",
      "Bird Watching",
      "Primate Viewing",
      "Butterfly Watching",
      "Camping"
    ],
    wildlife: ["Colobus Monkeys", "Red-tailed Monkeys", "Over 300 Bird Species", "Butterflies"],
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    gallery: [],
    tourCount: 6,
    hotelCount: 5,
    rating: 4.5,
    featured: false,
    flora: "Over 300 plant species"
  },
  {
    id: 33,
    name: "Mount Elgon National Park",
    slug: "mount-elgon",
    region: "Western",
    country: "Kenya",
    coordinates: { lat: 1.1167, lng: 34.6000 },
    description: "Extinct volcano with caves, waterfalls, and unique flora.",
    shortDescription: "Extinct volcano with caves",
    bestTimeToVisit: "June-September",
    weather: "Cool, 10-25°C",
    activities: [
      "Mountain Hiking",
      "Cave Exploration",
      "Waterfall Visits",
      "Bird Watching",
      "Camping"
    ],
    wildlife: ["Elephant", "Buffalo", "Hyena", "Leopard", "Monkeys"],
    image: "https://images.unsplash.com/photo-1547483238-f400e65ccd56",
    gallery: [],
    tourCount: 4,
    hotelCount: 3,
    rating: 4.4,
    featured: false,
    caves: "Kitum Cave, Makingeny Cave"
  },
  {
    id: 34,
    name: "Saiwa Swamp National Park",
    slug: "saiwa-swamp",
    region: "Western",
    country: "Kenya",
    coordinates: { lat: 1.1000, lng: 35.1000 },
    description: "Kenya's smallest national park, home to the rare Sitatunga antelope.",
    shortDescription: "Home of the rare Sitatunga antelope",
    bestTimeToVisit: "Year-round",
    weather: "Warm, 18-28°C",
    activities: [
      "Walking Safaris",
      "Bird Watching",
      "Boardwalk Trails",
      "Sitatunga Viewing"
    ],
    wildlife: ["Sitatunga Antelope", "Monkeys", "Otters", "Over 300 Bird Species"],
    image: "https://images.unsplash.com/photo-1549362157-6c7e6e3e33e4",
    gallery: [],
    tourCount: 3,
    hotelCount: 2,
    rating: 4.3,
    featured: false,
    area: "3 km²"
  },

  // CITIES & URBAN
  {
    id: 35,
    name: "Nairobi National Park",
    slug: "nairobi-national-park",
    region: "Nairobi",
    country: "Kenya",
    coordinates: { lat: -1.3733, lng: 36.8367 },
    description: "The only national park within a capital city, with wildlife against a city skyline.",
    shortDescription: "Wildlife with city skyline",
    bestTimeToVisit: "Year-round",
    weather: "Mild, 15-28°C",
    activities: [
      "Game Drives",
      "Sheldrick Elephant Orphanage",
      "Giraffe Center",
      "Safari Walk",
      "Bird Watching"
    ],
    wildlife: ["Lion", "Leopard", "Buffalo", "Rhino", "Giraffe", "Zebra"],
    image: "https://images.unsplash.com/photo-1549362157-6c7e6e3e33e4",
    gallery: [],
    tourCount: 10,
    hotelCount: 8,
    rating: 4.7,
    featured: true,
    unique: "Only national park within a capital city"
  },
  {
    id: 36,
    name: "Nairobi Giraffe Centre",
    slug: "giraffe-centre",
    region: "Nairobi",
    country: "Kenya",
    coordinates: { lat: -1.3750, lng: 36.7500 },
    description: "Conservation center for Rothschild giraffes where you can feed and kiss giraffes.",
    shortDescription: "Feed and kiss giraffes",
    bestTimeToVisit: "Year-round",
    weather: "Mild, 15-28°C",
    activities: [
      "Giraffe Feeding",
      "Educational Tours",
      "Nature Walks",
      "Bird Watching"
    ],
    wildlife: ["Rothschild Giraffes", "Warthogs", "Monkeys"],
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    gallery: [],
    tourCount: 5,
    hotelCount: 2,
    rating: 4.8,
    featured: true,
    conservation: "Rothschild giraffe breeding program"
  },
  {
    id: 37,
    name: "David Sheldrick Wildlife Trust",
    slug: "sheldrick-wildlife-trust",
    region: "Nairobi",
    country: "Kenya",
    coordinates: { lat: -1.3767, lng: 36.7450 },
    description: "World-famous elephant orphanage rescuing and rehabilitating orphaned elephants.",
    shortDescription: "Elephant orphanage",
    bestTimeToVisit: "11:00 AM daily for public viewing",
    weather: "Mild, 15-28°C",
    activities: [
      "Elephant Orphan Viewing",
      "Adopt an Elephant",
      "Educational Tours",
      "Photography"
    ],
    wildlife: ["Baby Elephants", "Rhinos"],
    image: "https://images.unsplash.com/photo-1549362157-6c7e6e3e33e4",
    gallery: [],
    tourCount: 4,
    hotelCount: 0,
    rating: 4.9,
    featured: true,
    adoption: "Elephant adoption program available"
  },
  {
    id: 38,
    name: "Nairobi National Museum",
    slug: "nairobi-museum",
    region: "Nairobi",
    country: "Kenya",
    coordinates: { lat: -1.2750, lng: 36.8167 },
    description: "Kenya's premier museum showcasing art, culture, and natural history.",
    shortDescription: "Kenya's cultural heritage",
    bestTimeToVisit: "Year-round",
    weather: "Indoor activity",
    activities: [
      "Museum Tours",
      "Art Exhibitions",
      "Botanical Gardens",
      "Snake Park Visit"
    ],
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    gallery: [],
    tourCount: 3,
    hotelCount: 0,
    rating: 4.5,
    featured: false,
    collections: ["Paleontology", "Ethnography", "Art"]
  },

  // More Coastal & Island Destinations
  {
    id: 39,
    name: "Mombasa Old Town",
    slug: "mombasa-old-town",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -4.0500, lng: 39.6667 },
    description: "Historic Swahili town with ancient architecture, markets, and Fort Jesus.",
    shortDescription: "Ancient Swahili heritage",
    bestTimeToVisit: "Year-round",
    weather: "Tropical, 25-32°C",
    activities: [
      "Fort Jesus Tour",
      "Street Walks",
      "Market Visits",
      "Cultural Tours",
      "Swahili Cuisine"
    ],
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd",
    gallery: [],
    tourCount: 8,
    hotelCount: 12,
    rating: 4.6,
    featured: true,
    unesco: "Fort Jesus is UNESCO World Heritage"
  },
  {
    id: 40,
    name: "Fort Jesus",
    slug: "fort-jesus",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -4.0625, lng: 39.6800 },
    description: "16th-century Portuguese fort, UNESCO World Heritage Site.",
    shortDescription: "UNESCO Portuguese fortress",
    bestTimeToVisit: "Year-round",
    weather: "Tropical",
    activities: [
      "Historical Tours",
      "Museum Visit",
      "Architecture Viewing",
      "Sunset Views"
    ],
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd",
    gallery: [],
    tourCount: 5,
    hotelCount: 0,
    rating: 4.7,
    featured: true,
    unesco: true,
    built: "1593-1596"
  },
  {
    id: 41,
    name: "Wasini Island",
    slug: "wasini-island",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -4.6667, lng: 39.3833 },
    description: "Island paradise with coral gardens, dolphin watching, and Swahili culture.",
    shortDescription: "Dolphin watching paradise",
    bestTimeToVisit: "October-March",
    weather: "Tropical",
    activities: [
      "Dolphin Watching",
      "Snorkeling",
      "Boat Trips",
      "Swahili Cooking",
      "Coral Gardens"
    ],
    wildlife: ["Dolphins", "Sea Turtles", "Tropical Fish"],
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd",
    gallery: [],
    tourCount: 6,
    hotelCount: 3,
    rating: 4.7,
    featured: false
  },
  {
    id: 42,
    name: "Kisite Marine National Park",
    slug: "kisite-marine",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -4.7167, lng: 39.3833 },
    description: "Marine protected area with pristine coral reefs and abundant marine life.",
    shortDescription: "Pristine coral reefs",
    bestTimeToVisit: "October-March",
    weather: "Tropical",
    activities: [
      "Snorkeling",
      "Scuba Diving",
      "Dolphin Watching",
      "Glass Bottom Boats"
    ],
    wildlife: ["Dolphins", "Sea Turtles", "Whale Sharks", "Tropical Fish"],
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206",
    gallery: [],
    tourCount: 5,
    hotelCount: 0,
    rating: 4.8,
    featured: true
  },

  // More Northern & Remote Destinations
  {
    id: 43,
    name: "Lake Logipi",
    slug: "lake-logipi",
    region: "Northern",
    country: "Kenya",
    coordinates: { lat: 2.2333, lng: 36.6167 },
    description: "Remote alkaline lake in the Suguta Valley, known for flamingos.",
    shortDescription: "Remote alkaline lake",
    bestTimeToVisit: "June-October",
    weather: "Extremely hot",
    activities: [
      "Photography",
      "Bird Watching",
      "Camping",
      "Remote Exploration"
    ],
    wildlife: ["Flamingos", "Birds"],
    image: "https://images.unsplash.com/photo-1455218873509-8097305ee378",
    gallery: [],
    tourCount: 1,
    hotelCount: 0,
    rating: 4.2,
    featured: false
  },
  {
    id: 44,
    name: "Central Island National Park",
    slug: "central-island",
    region: "Northern",
    country: "Kenya",
    coordinates: { lat: 3.5000, lng: 36.0000 },
    description: "Volcanic island in Lake Turkana with crater lakes and crocodiles.",
    shortDescription: "Volcanic island in the Jade Sea",
    bestTimeToVisit: "June-September",
    weather: "Extremely hot",
    activities: [
      "Boat Trips",
      "Crater Lake Visits",
      "Bird Watching",
      "Camping"
    ],
    wildlife: ["Crocodiles", "Birds", "Turtles"],
    image: "https://images.unsplash.com/photo-1549362157-6c7e6e3e33e4",
    gallery: [],
    tourCount: 2,
    hotelCount: 0,
    rating: 4.4,
    featured: false
  },
  {
    id: 45,
    name: "Sibiloi National Park",
    slug: "sibiloi",
    region: "Northern",
    country: "Kenya",
    coordinates: { lat: 3.9667, lng: 36.3333 },
    description: "Fossil-rich area on Lake Turkana, known as the 'Cradle of Mankind'.",
    shortDescription: "Fossil-rich 'Cradle of Mankind'",
    bestTimeToVisit: "June-September",
    weather: "Extremely hot",
    activities: [
      "Fossil Hunting",
      "Paleontology Sites",
      "Game Drives",
      "Lake Views"
    ],
    wildlife: ["Zebra", "Oryx", "Gerenuk", "Birds"],
    image: "https://images.unsplash.com/photo-1523805009345-7448845a9e53",
    gallery: [],
    tourCount: 2,
    hotelCount: 1,
    rating: 4.3,
    featured: false,
    unesco: true
  },
  {
    id: 46,
    name: "Kora National Park",
    slug: "kora",
    region: "Eastern",
    country: "Kenya",
    coordinates: { lat: -0.1667, lng: 38.6667 },
    description: "Former home of conservationist George Adamson, 'Born Free' fame.",
    shortDescription: "George Adamson's former home",
    bestTimeToVisit: "June-October",
    weather: "Hot",
    activities: [
      "Game Drives",
      "Adamson's Grave Visit",
      "Bird Watching",
      "Camping"
    ],
    wildlife: ["Elephant", "Lion", "Leopard", "Buffalo"],
    image: "https://images.unsplash.com/photo-1549362157-6c7e6e3e33e4",
    gallery: [],
    tourCount: 3,
    hotelCount: 1,
    rating: 4.4,
    featured: false
  },
  {
    id: 47,
    name: "Ruma National Park",
    slug: "ruma",
    region: "Nyanza",
    country: "Kenya",
    coordinates: { lat: -0.6333, lng: 34.3500 },
    description: "Home to the rare Roan Antelope, the only place to see them in Kenya.",
    shortDescription: "Home of the rare Roan Antelope",
    bestTimeToVisit: "June-October",
    weather: "Warm",
    activities: [
      "Game Drives",
      "Roan Antelope Viewing",
      "Bird Watching",
      "Picnicking"
    ],
    wildlife: ["Roan Antelope", "Elephant", "Buffalo", "Giraffe"],
    image: "https://images.unsplash.com/photo-1523805009345-7448845a9e53",
    gallery: [],
    tourCount: 3,
    hotelCount: 1,
    rating: 4.3,
    featured: false,
    unique: "Only place for Roan Antelope in Kenya"
  },
  {
    id: 48,
    name: "Mwingi National Reserve",
    slug: "mwingi",
    region: "Eastern",
    country: "Kenya",
    coordinates: { lat: -0.5000, lng: 38.3000 },
    description: "Remote wilderness with baobab trees and diverse wildlife.",
    shortDescription: "Baobab-studded wilderness",
    bestTimeToVisit: "June-October",
    weather: "Hot",
    activities: [
      "Game Drives",
      "Bird Watching",
      "Bush Walks",
      "Photography"
    ],
    wildlife: ["Elephant", "Lion", "Leopard", "Giraffe", "Buffalo"],
    image: "https://images.unsplash.com/photo-1549362157-6c7e6e3e33e4",
    gallery: [],
    tourCount: 2,
    hotelCount: 1,
    rating: 4.1,
    featured: false
  },
  {
    id: 49,
    name: "Bisanadi National Reserve",
    slug: "bisanadi",
    region: "Eastern",
    country: "Kenya",
    coordinates: { lat: 0.1000, lng: 38.8000 },
    description: "Remote reserve adjacent to Meru National Park, wild and undeveloped.",
    shortDescription: "Wild and undeveloped",
    bestTimeToVisit: "June-October",
    weather: "Hot",
    activities: [
      "Game Drives",
      "Bush Camping",
      "Bird Watching",
      "Remote Safaris"
    ],
    wildlife: ["Elephant", "Lion", "Leopard", "Buffalo"],
    image: "https://images.unsplash.com/photo-1523805009345-7448845a9e53",
    gallery: [],
    tourCount: 1,
    hotelCount: 0,
    rating: 4.0,
    featured: false
  },
  {
    id: 50,
    name: "Nasolot National Reserve",
    slug: "nasolot",
    region: "Rift Valley",
    country: "Kenya",
    coordinates: { lat: 1.3000, lng: 35.1000 },
    description: "Scenic reserve with dramatic cliffs and riverine forest.",
    shortDescription: "Dramatic cliffs and riverine forest",
    bestTimeToVisit: "June-October",
    weather: "Hot",
    activities: [
      "Game Drives",
      "Bird Watching",
      "Walking Safaris",
      "Photography"
    ],
    wildlife: ["Elephant", "Buffalo", "Leopard", "Monkeys"],
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    gallery: [],
    tourCount: 2,
    hotelCount: 1,
    rating: 4.2,
    featured: false
  },
  {
    id: 51,
    name: "South Island National Park",
    slug: "south-island",
    region: "Northern",
    country: "Kenya",
    coordinates: { lat: 2.6333, lng: 36.6000 },
    description: "Volcanic island in Lake Turkana with stunning landscapes and crocodiles.",
    shortDescription: "Volcanic island in Lake Turkana",
    bestTimeToVisit: "June-September",
    weather: "Extremely hot",
    activities: [
      "Boat Trips",
      "Volcano Exploration",
      "Bird Watching",
      "Camping"
    ],
    wildlife: ["Crocodiles", "Birds", "Turtles"],
    image: "https://images.unsplash.com/photo-1549362157-6c7e6e3e33e4",
    gallery: [],
    tourCount: 1,
    hotelCount: 0,
    rating: 4.2,
    featured: false
  },
  {
    id: 52,
    name: "Malka Mari National Park",
    slug: "malka-mari",
    region: "Eastern",
    country: "Kenya",
    coordinates: { lat: 3.8667, lng: 41.2000 },
    description: "Remote park near the Ethiopian border with unique riverine ecosystem.",
    shortDescription: "Remote border park",
    bestTimeToVisit: "June-September",
    weather: "Hot",
    activities: [
      "Game Drives",
      "Bird Watching",
      "River Safaris",
      "Camping"
    ],
    wildlife: ["Giraffe", "Zebra", "Oryx", "Birds"],
    image: "https://images.unsplash.com/photo-1523805009345-7448845a9e53",
    gallery: [],
    tourCount: 1,
    hotelCount: 0,
    rating: 4.0,
    featured: false
  },

  // More Coastal & Island Gems
  {
    id: 53,
    name: "Chale Island",
    slug: "chale-island",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -4.4167, lng: 39.4500 },
    description: "Private island paradise with luxury resort and sacred forest.",
    shortDescription: "Private island paradise",
    bestTimeToVisit: "December-March",
    weather: "Tropical",
    activities: [
      "Snorkeling",
      "Diving",
      "Spa Treatments",
      "Forest Walks",
      "Kayaking"
    ],
    wildlife: ["Sea Turtles", "Dolphins", "Monkeys", "Birds"],
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd",
    gallery: [],
    tourCount: 4,
    hotelCount: 2,
    rating: 4.8,
    featured: false,
    private: true
  },
  {
    id: 54,
    name: "Manda Island",
    slug: "manda-island",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -2.2500, lng: 40.9167 },
    description: "Ancient Swahili settlement with ruins and pristine beaches.",
    shortDescription: "Ancient Swahili ruins",
    bestTimeToVisit: "July-March",
    weather: "Tropical",
    activities: [
      "Historical Tours",
      "Beach Activities",
      "Dhow Cruises",
      "Snorkeling"
    ],
    wildlife: ["Marine Life", "Birds"],
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd",
    gallery: [],
    tourCount: 3,
    hotelCount: 2,
    rating: 4.6,
    featured: false,
    archaeological: "Takwa Ruins"
  },
  {
    id: 55,
    name: "Pate Island",
    slug: "pate-island",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -2.1000, lng: 41.0500 },
    description: "Historic island with Swahili ruins and rich cultural heritage.",
    shortDescription: "Historic Swahili ruins",
    bestTimeToVisit: "July-March",
    weather: "Tropical",
    activities: [
      "Archaeological Tours",
      "Cultural Visits",
      "Boat Trips",
      "Walking Tours"
    ],
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd",
    gallery: [],
    tourCount: 2,
    hotelCount: 1,
    rating: 4.4,
    featured: false
  },
  {
    id: 56,
    name: "Kiunga Marine National Reserve",
    slug: "kiunga-marine",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -1.7500, lng: 41.3500 },
    description: "Remote marine reserve with pristine coral reefs and turtle nesting sites.",
    shortDescription: "Pristine marine reserve",
    bestTimeToVisit: "October-March",
    weather: "Tropical",
    activities: [
      "Snorkeling",
      "Diving",
      "Turtle Watching",
      "Boat Safaris"
    ],
    wildlife: ["Sea Turtles", "Dolphins", "Whale Sharks", "Coral"],
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206",
    gallery: [],
    tourCount: 2,
    hotelCount: 1,
    rating: 4.5,
    featured: false
  },
  {
    id: 57,
    name: "Dodori National Reserve",
    slug: "dodori",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -1.9167, lng: 41.1667 },
    description: "Coastal forest and mangrove reserve, home to rare bird species.",
    shortDescription: "Coastal forest and mangroves",
    bestTimeToVisit: "June-October",
    weather: "Tropical",
    activities: [
      "Bird Watching",
      "Boat Safaris",
      "Mangrove Walks",
      "Game Drives"
    ],
    wildlife: ["Topi", "Elephant", "Buffalo", "Rare Birds"],
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd",
    gallery: [],
    tourCount: 1,
    hotelCount: 0,
    rating: 4.2,
    featured: false
  },
  {
    id: 58,
    name: "Boni National Reserve",
    slug: "boni",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -1.7000, lng: 41.3000 },
    description: "Remote coastal forest reserve with unique wildlife and culture.",
    shortDescription: "Remote coastal forest",
    bestTimeToVisit: "June-October",
    weather: "Tropical",
    activities: [
      "Bird Watching",
      "Game Drives",
      "Cultural Visits",
      "Walking Safaris"
    ],
    wildlife: ["Elephant", "Buffalo", "Leopard", "Unique Birds"],
    image: "https://images.unsplash.com/photo-1523805009345-7448845a9e53",
    gallery: [],
    tourCount: 1,
    hotelCount: 0,
    rating: 4.1,
    featured: false
  },

  // More Mountain & Highland Destinations
  {
    id: 59,
    name: "Cherangani Hills",
    slug: "cherangani-hills",
    region: "Rift Valley",
    country: "Kenya",
    coordinates: { lat: 1.1000, lng: 35.5000 },
    description: "Mountain range with forests, waterfalls, and hiking trails.",
    shortDescription: "Hiking paradise",
    bestTimeToVisit: "June-October",
    weather: "Cool",
    activities: [
      "Hiking",
      "Bird Watching",
      "Waterfall Visits",
      "Forest Walks"
    ],
    wildlife: ["Monkeys", "Birds", "Butterflies"],
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    gallery: [],
    tourCount: 3,
    hotelCount: 2,
    rating: 4.4,
    featured: false
  },
  {
    id: 60,
    name: "Taita Hills",
    slug: "taita-hills",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -3.4000, lng: 38.3333 },
    description: "Mountain range with unique endemic species and spectacular views.",
    shortDescription: "Endemic species paradise",
    bestTimeToVisit: "June-October",
    weather: "Cool",
    activities: [
      "Hiking",
      "Bird Watching",
      "Butterfly Watching",
      "Forest Walks"
    ],
    wildlife: ["Taita Thrush", "Taita Apalis", "Monkeys"],
    image: "https://images.unsplash.com/photo-1547483238-f400e65ccd56",
    gallery: [],
    tourCount: 3,
    hotelCount: 2,
    rating: 4.5,
    featured: false,
    endemics: "Several endemic bird species"
  },
  {
    id: 61,
    name: "Ndotos Mountains",
    slug: "ndotos",
    region: "Rift Valley",
    country: "Kenya",
    coordinates: { lat: 0.9333, lng: 36.3500 },
    description: "Wild mountain range with unique wildlife and walking safaris.",
    shortDescription: "Wild mountain range",
    bestTimeToVisit: "June-October",
    weather: "Cool",
    activities: [
      "Walking Safaris",
      "Bird Watching",
      "Game Drives",
      "Cultural Visits"
    ],
    wildlife: ["Elephant", "Buffalo", "Leopard", "Greater Kudu"],
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    gallery: [],
    tourCount: 2,
    hotelCount: 1,
    rating: 4.3,
    featured: false
  },
  {
    id: 62,
    name: "Mathews Range",
    slug: "mathews-range",
    region: "Rift Valley",
    country: "Kenya",
    coordinates: { lat: 1.1000, lng: 37.2000 },
    description: "Remote mountain range with forest and unique wildlife species.",
    shortDescription: "Remote mountain wilderness",
    bestTimeToVisit: "June-October",
    weather: "Cool",
    activities: [
      "Walking Safaris",
      "Bird Watching",
      "Game Drives",
      "Cultural Visits"
    ],
    wildlife: ["Elephant", "Greater Kudu", "Leopard", "Wild Dog"],
    image: "https://images.unsplash.com/photo-1547483238-f400e65ccd56",
    gallery: [],
    tourCount: 2,
    hotelCount: 2,
    rating: 4.5,
    featured: false
  },
  {
    id: 63,
    name: "Ngong Hills",
    slug: "ngong-hills",
    region: "Nairobi",
    country: "Kenya",
    coordinates: { lat: -1.4000, lng: 36.6333 },
    description: "Scenic hills near Nairobi with hiking trails and panoramic views.",
    shortDescription: "Hiking with Nairobi views",
    bestTimeToVisit: "Year-round",
    weather: "Mild",
    activities: [
      "Hiking",
      "Picnicking",
      "Paragliding",
      "Bird Watching"
    ],
    wildlife: ["Birds", "Monkeys"],
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    gallery: [],
    tourCount: 4,
    hotelCount: 0,
    rating: 4.5,
    featured: false
  },
  {
    id: 64,
    name: "Satima Peak",
    slug: "satima-peak",
    region: "Central",
    country: "Kenya",
    coordinates: { lat: -0.3500, lng: 36.6167 },
    description: "Highest peak in the Aberdare Range with moorlands and unique vegetation.",
    shortDescription: "Highest in Aberdare Range",
    bestTimeToVisit: "June-October",
    weather: "Cold",
    activities: [
      "Hiking",
      "Mountain Climbing",
      "Bird Watching",
      "Camping"
    ],
    wildlife: ["Elephant", "Buffalo", "Bongo"],
    image: "https://images.unsplash.com/photo-1547483238-f400e65ccd56",
    gallery: [],
    tourCount: 2,
    hotelCount: 1,
    rating: 4.4,
    featured: false,
    altitude: "4,001 m"
  },

  // Additional Unique Destinations
  {
    id: 65,
    name: "Kisumu Impala Sanctuary",
    slug: "kisumu-impala",
    region: "Nyanza",
    country: "Kenya",
    coordinates: { lat: -0.1000, lng: 34.7500 },
    description: "Wildlife sanctuary on Lake Victoria with impalas, zebras, and birdlife.",
    shortDescription: "Lake Victoria wildlife",
    bestTimeToVisit: "Year-round",
    weather: "Warm",
    activities: [
      "Game Viewing",
      "Bird Watching",
      "Walking Safaris",
      "Picnicking"
    ],
    wildlife: ["Impala", "Zebra", "Giraffe", "Birds"],
    image: "https://images.unsplash.com/photo-1549362157-6c7e6e3e33e4",
    gallery: [],
    tourCount: 3,
    hotelCount: 2,
    rating: 4.3,
    featured: false
  },
  {
    id: 66,
    name: "Ndere Island National Park",
    slug: "ndere-island",
    region: "Nyanza",
    country: "Kenya",
    coordinates: { lat: -0.2000, lng: 34.5500 },
    description: "Small island in Lake Victoria with scenic views and birdlife.",
    shortDescription: "Lake Victoria island",
    bestTimeToVisit: "Year-round",
    weather: "Warm",
    activities: [
      "Boat Trips",
      "Bird Watching",
      "Walking Safaris",
      "Picnicking"
    ],
    wildlife: ["Hippos", "Crocodiles", "Birds"],
    image: "https://images.unsplash.com/photo-1519046904884-53103b34b206",
    gallery: [],
    tourCount: 2,
    hotelCount: 0,
    rating: 4.2,
    featured: false
  },
  {
    id: 67,
    name: "Mfangano Island",
    slug: "mfangano-island",
    region: "Nyanza",
    country: "Kenya",
    coordinates: { lat: -0.4667, lng: 34.0167 },
    description: "Lake Victoria island with ancient rock art and fishing villages.",
    shortDescription: "Ancient rock art",
    bestTimeToVisit: "December-March",
    weather: "Warm",
    activities: [
      "Rock Art Tours",
      "Cultural Visits",
      "Boat Trips",
      "Fishing"
    ],
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd",
    gallery: [],
    tourCount: 2,
    hotelCount: 2,
    rating: 4.3,
    featured: false,
    rockArt: "Ancient rock paintings"
  },
  {
    id: 68,
    name: "Rusinga Island",
    slug: "rusinga-island",
    region: "Nyanza",
    country: "Kenya",
    coordinates: { lat: -0.4000, lng: 34.1667 },
    description: "Lake Victoria island known for fossil sites and beautiful beaches.",
    shortDescription: "Fossil island",
    bestTimeToVisit: "December-March",
    weather: "Warm",
    activities: [
      "Fossil Hunting",
      "Beach Activities",
      "Bird Watching",
      "Boat Trips"
    ],
    wildlife: ["Birds", "Hippos"],
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd",
    gallery: [],
    tourCount: 2,
    hotelCount: 2,
    rating: 4.4,
    featured: false,
    paleontology: "Miocene fossils"
  },
  {
    id: 69,
    name: "Hell's Kitchen",
    slug: "hells-kitchen",
    region: "Rift Valley",
    country: "Kenya",
    coordinates: { lat: -0.8833, lng: 36.3167 },
    description: "Spectacular gorge in Hell's Gate National Park with hot springs.",
    shortDescription: "Spectacular gorge",
    bestTimeToVisit: "Year-round",
    weather: "Warm",
    activities: [
      "Gorge Walking",
      "Hot Springs",
      "Rock Climbing",
      "Photography"
    ],
    image: "https://images.unsplash.com/photo-1549362157-6c7e6e3e33e4",
    gallery: [],
    tourCount: 3,
    hotelCount: 0,
    rating: 4.6,
    featured: false
  },
  {
    id: 70,
    name: "Olorgesailie Prehistoric Site",
    slug: "olorgesailie",
    region: "Rift Valley",
    country: "Kenya",
    coordinates: { lat: -1.5833, lng: 36.4500 },
    description: "Important archaeological site with hand axes and fossils.",
    shortDescription: "Prehistoric site",
    bestTimeToVisit: "Year-round",
    weather: "Warm",
    activities: [
      "Archaeological Tours",
      "Museum Visit",
      "Educational Tours"
    ],
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    gallery: [],
    tourCount: 2,
    hotelCount: 0,
    rating: 4.3,
    featured: false,
    archaeological: "Acheulean hand axes"
  },
  {
    id: 71,
    name: "Koobi Fora",
    slug: "koobi-fora",
    region: "Northern",
    country: "Kenya",
    coordinates: { lat: 3.9500, lng: 36.2000 },
    description: "World-famous paleontological site in the Turkana Basin.",
    shortDescription: "Famous fossil site",
    bestTimeToVisit: "June-September",
    weather: "Hot",
    activities: [
      "Paleontology Tours",
      "Fossil Hunting",
      "Educational Tours"
    ],
    image: "https://images.unsplash.com/photo-1523805009345-7448845a9e53",
    gallery: [],
    tourCount: 1,
    hotelCount: 0,
    rating: 4.5,
    featured: false,
    unesco: true
  },
  {
    id: 72,
    name: "Thimlich Ohinga",
    slug: "thimlich-ohinga",
    region: "Nyanza",
    country: "Kenya",
    coordinates: { lat: -0.9000, lng: 34.2500 },
    description: "UNESCO World Heritage dry-stone walled settlement.",
    shortDescription: "UNESCO stone ruins",
    bestTimeToVisit: "Year-round",
    weather: "Warm",
    activities: [
      "Archaeological Tours",
      "Cultural Visits",
      "Educational Tours"
    ],
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    gallery: [],
    tourCount: 2,
    hotelCount: 1,
    rating: 4.4,
    featured: false,
    unesco: true
  },
  {
    id: 73,
    name: "Gede Ruins",
    slug: "gede-ruins",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -3.3083, lng: 40.0167 },
    description: "Well-preserved Swahili town ruins from the 12th century.",
    shortDescription: "Ancient Swahili ruins",
    bestTimeToVisit: "Year-round",
    weather: "Tropical",
    activities: [
      "Historical Tours",
      "Archaeological Tours",
      "Museum Visit",
      "Forest Walks"
    ],
    wildlife: ["Monkeys", "Birds"],
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd",
    gallery: [],
    tourCount: 3,
    hotelCount: 2,
    rating: 4.6,
    featured: true
  },
  {
    id: 74,
    name: "Takwa Ruins",
    slug: "takwa-ruins",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -2.2500, lng: 40.9000 },
    description: "Ancient Swahili settlement ruins on Manda Island.",
    shortDescription: "Ancient Swahili settlement",
    bestTimeToVisit: "July-March",
    weather: "Tropical",
    activities: [
      "Archaeological Tours",
      "Boat Trips",
      "Historical Tours"
    ],
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd",
    gallery: [],
    tourCount: 2,
    hotelCount: 0,
    rating: 4.4,
    featured: false
  },
  {
    id: 75,
    name: "Jumba Ruins",
    slug: "jumba-ruins",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -3.9500, lng: 39.7333 },
    description: "15th-century Swahili settlement ruins near Mombasa.",
    shortDescription: "15th-century Swahili ruins",
    bestTimeToVisit: "Year-round",
    weather: "Tropical",
    activities: [
      "Historical Tours",
      "Archaeological Tours",
      "Photography"
    ],
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd",
    gallery: [],
    tourCount: 2,
    hotelCount: 0,
    rating: 4.3,
    featured: false
  },
  {
    id: 76,
    name: "Shimoni Slave Caves",
    slug: "shimoni-caves",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -4.6500, lng: 39.3833 },
    description: "Historic slave caves with dark history and bat colonies.",
    shortDescription: "Historic slave caves",
    bestTimeToVisit: "Year-round",
    weather: "Tropical",
    activities: [
      "Historical Tours",
      "Cave Exploration",
      "Educational Tours"
    ],
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    gallery: [],
    tourCount: 2,
    hotelCount: 1,
    rating: 4.4,
    featured: false,
    historical: "Slave trade history"
  },
  {
    id: 77,
    name: "Kaya Kinondo Sacred Forest",
    slug: "kaya-kinondo",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -4.4000, lng: 39.5333 },
    description: "Sacred Mijikenda forest, UNESCO World Heritage Site.",
    shortDescription: "UNESCO sacred forest",
    bestTimeToVisit: "Year-round",
    weather: "Tropical",
    activities: [
      "Cultural Tours",
      "Forest Walks",
      "Bird Watching",
      "Educational Tours"
    ],
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    gallery: [],
    tourCount: 2,
    hotelCount: 0,
    rating: 4.5,
    featured: false,
    unesco: true
  },
  {
    id: 78,
    name: "Arabuko Sokoke Forest",
    slug: "arabuko-sokoke",
    region: "Coast",
    country: "Kenya",
    coordinates: { lat: -3.3167, lng: 39.9833 },
    description: "Largest remaining coastal forest in East Africa, birding paradise.",
    shortDescription: "Coastal forest paradise",
    bestTimeToVisit: "Year-round",
    weather: "Tropical",
    activities: [
      "Bird Watching",
      "Forest Walks",
      "Butterfly Watching",
      "Nature Tours"
    ],
    wildlife: ["Golden-rumped Elephant Shrew", "Sokoke Scops Owl", "Ader's Duiker"],
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    gallery: [],
    tourCount: 4,
    hotelCount: 2,
    rating: 4.7,
    featured: true,
    endemics: "Several endemic species"
  },
  {
    id: 79,
    name: "Kakapel Rock Art",
    slug: "kakapel-rock-art",
    region: "Western",
    country: "Kenya",
    coordinates: { lat: 1.2000, lng: 34.1500 },
    description: "Ancient rock art site with over 500 paintings.",
    shortDescription: "Ancient rock art",
    bestTimeToVisit: "Year-round",
    weather: "Warm",
    activities: [
      "Rock Art Tours",
      "Cultural Visits",
      "Archaeological Tours"
    ],
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    gallery: [],
    tourCount: 1,
    hotelCount: 0,
    rating: 4.3,
    featured: false
  },
  {
    id: 80,
    name: "Namanga",
    slug: "namanga",
    region: "Rift Valley",
    country: "Kenya",
    coordinates: { lat: -2.5500, lng: 36.8000 },
    description: "Border town with spectacular views of Mount Kilimanjaro.",
    shortDescription: "Kilimanjaro views",
    bestTimeToVisit: "June-October",
    weather: "Warm",
    activities: [
      "Kilimanjaro Viewing",
      "Market Visits",
      "Cultural Tours"
    ],
    image: "https://images.unsplash.com/photo-1547483238-f400e65ccd56",
    gallery: [],
    tourCount: 2,
    hotelCount: 3,
    rating: 4.2,
    featured: false
  }
];